#!/usr/bin/env bash
# While loop and if statement
#  On the 9th iteration, displays "Hi" before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "hi"
  fi 
  echo "Best school"
  (( count++ ))
done 
